'use strict';

globalThis.AFTER_ANSWERS = Object.freeze({
  1: "Treat discomfort as a warning when it points to a real problem you can name and act on; treat it as noise when it adds pain without useful direction.",
  2: "Delay is reasonable when you need a short time to prepare and no irreversible choice depends on it; it becomes avoidance when comfort is the only reason to wait.",
  3: "People confuse them when a feeling is treated as proof of its cause, or a measurement is treated as proof of the whole explanation.",
  4: "The tie should break toward the source with the most current, direct, verifiable evidence about the exact situation.",
  5: "A personal experience can strongly establish what you felt and how it affected you; claims about outside reality still need evidence others can check.",
  6: "You can act without certainty when the available evidence clearly favours one option and waiting carries its own cost.",
  7: "Name the mistake clearly, explain why it matters, show the correction, and protect the person's dignity so questions still feel safe.",
  8: "General expertise should lose when a competent direct inspection provides stronger case-specific evidence that explains the actual problem.",
  9: "Depart from the literal wording only when reliable context, updated information, or the rule's purpose shows that a literal reading would misapply it.",
  10: "Several sources become stronger when they are genuinely independent, preserve different evidence, and still converge after cross-checking.",
  11: "It happens when a technical explanation is used to dismiss the real-world harm, responsibility, or practical problem that still exists.",
  12: "The beliefs most worth rechecking are the ones you absorbed before you could question them and still follow mainly because they feel normal.",
  13: "Context is a real difference when it changes the relevant harm, purpose, or responsibility; it is just habit when ‘we do it this way’ is the whole defence.",
  14: "Full consent protects against coercion and deception, but exploitation, unfairness, predictable harm, and abuse of weakness can still remain.",
  15: "Anything legal that needlessly humiliates, exploits, deceives, or harms someone can still be worth refusing simply because being allowed is not enough.",
  16: "Say what the evidence suggests, how confident you are, what could still change, and update the claim when better evidence arrives.",
  17: "Revise when credible counterevidence survives serious checking, and change only the part of the belief that the new evidence actually defeats.",
  18: "A strong, relevant pattern can justify limited extra screening, but accusation or punishment should still require evidence about the individual.",
  19: "Treat the connection as a lead, test direct links, and make only the smallest coordination claim the evidence can actually prove.",
  20: "Use temporary, reversible safeguards that match the known risk, and be explicit that a precaution is not a final verdict.",
  21: "Verify what you can quickly, state exactly what is uncertain, recommend low-cost precautions if needed, and update people as facts improve.",
  22: "Words like fairness, freedom, harm, respect, success, safety, and responsibility cause trouble because people often argue before agreeing what they mean.",
  23: "Shared good outcomes can show that a practice helps without proving the deeper explanation, especially when several different causes could produce the same result.",
  24: "Agreement on values or useful practices shows real common ground; it does not make incompatible claims about reality or destination the same.",
  25: "Repurposing is clever when the new use respects the object's core function and safety; it becomes sabotage when it defeats what the thing was built to do.",
  26: "More is worth the time when it serves a clear purpose that matters more than the hours it costs; otherwise it is just a pricier treadmill.",
  27: "Removing temptation is useful when control is weak; staying around it is the stronger test once you can reliably choose not to obey it.",
  28: "The user owns choices and habits, while the designer owns deliberate features that predictably exploit weakness or make self-control harder.",
  29: "Silence often reveals the worries, decisions, regrets, and desires that constant stimulation keeps from reaching the front of your mind.",
  30: "Useful app time serves a specific purpose you would choose deliberately; compulsive feed time is the part you keep doing mainly because stopping feels harder than continuing.",
  31: "Future upside should outweigh an existing pattern only when there is concrete evidence the person is already changing, not merely promising to.",
  32: "Proving fault matters for justice, repair, and cost; it becomes a distraction when it replaces action on the part of the problem you can actually solve.",
  33: "Delay helps when it gathers information, cools emotion, or improves preparation; it gets expensive when nothing improves except the temporary feeling of relief.",
  34: "A useful delay must produce something: better information, preparation, savings, healing, skill, or a clear review point.",
  35: "Publicity serves the cause when it clearly increases the good and you would still support the cause without the attention.",
  36: "Extra verification is sensible when the source has a weaker track record or the stakes are high; it becomes status bias when the same evidence would be accepted from someone prestigious.",
  37: "Say the truth accurately, at the right time, for a real reason, and in a way that helps the person act on it instead of humiliating them.",
  38: "Self-control matters more when raw power can harm others, because strength that cannot govern itself becomes a risk to the people around it.",
  39: "External motivators help when they get you moving toward something you already value; they become the reason when the habit collapses without applause or points.",
  40: "Do the minimum that prevents avoidable harm tomorrow, then rest without guilt; restorative rest should not quietly create the next emergency.",
  41: "A sacrifice is truly temporary when it has a clear end point and recovery plan; it becomes the new normal when the exception keeps renewing itself.",
  42: "A rare opportunity can justify a limited, understood cost, but not a cost likely to create lasting damage that outweighs the achievement.",
  43: "Time with family, real rest, health, learning, service, and deep enjoyment can look more valuable; empty scrolling can look less valuable.",
  44: "The small repeated choice that deserves attention is the one whose daily effect seems tiny but compounds across money, health, attention, or relationships.",
  45: "A social crutch becomes a requirement when you start feeling unable to function normally without it and stop building the underlying skill.",
  46: "Responsibility is shared: the user owns choices, while the designer carries extra responsibility for knowingly building systems that exploit predictable weakness.",
  47: "Escalation is a warning sign when you need more intensity just to feel what the old level used to give you.",
  48: "Replace something that still works when the practical gain is large, recurring, and worth the full cost after novelty and status are stripped away.",
  49: "You would likely choose more for usefulness, comfort, quality, and personal enjoyment, and less for whatever mainly exists to signal status.",
  50: "A habit is part of success when removing it reliably hurts the results; if performance stays the same, it may just be standing near success in good lighting.",
  51: "Set standards around character, effort, responsibility, compatibility, and specific unmet needs, not a collage of the best traits from different people.",
  52: "Copy practices that clearly improve your family's real life; do not copy routines whose hidden cost, temperament, or circumstances you do not understand.",
  53: "Use repeated experience to identify your own patterns and warning signs, then stop there unless broader evidence actually supports a claim about everyone else.",
  54: "Workable differences are preferences that can be negotiated without violating core values; structural differences shape children, money, family boundaries, or the household's direction.",
  55: "A caring partner should notice repeated needs and obvious responsibilities; personal preferences, hidden expectations, and unusual priorities should usually be said out loud.",
  56: "Prolonged absence is worth it only when the financial need is serious, the time is limited, and the relationship costs remain manageable and actively cared for.",
  57: "Helpful flexibility has clear review points and conditions for ending or extending the plan; harmful flexibility just keeps postponing the decision because each extension feels easier.",
  58: "The shared-home option needs protected privacy, clear decision boundaries, respectful limits on interference, and a realistic exit plan.",
  59: "Own your wrong without excuses, then discuss the other person's separate wrong afterward instead of using it to reduce your responsibility.",
  60: "An exception is compassionate when it responds to a real need without making the tantrum the reason the rule changed.",
  61: "Use screens heavily when the situation is unusually demanding or the tool has a clear purpose; keep ordinary waiting and boredom as practice for self-control.",
  62: "An exception is healthy when both parents agree on the reason and the child learns it is a special case, not a way to play parents against each other.",
  63: "Escalate first when there is credible danger, repeated serious harm, or evidence direct contact is unsafe; otherwise clarify directly before recruiting an audience.",
  64: "A believable trajectory is repeated change supported by effort and time; imagining a different person means expecting commitment to erase stable values or incompatibilities.",
  65: "Help earns a reasonable voice when the helper bears real cost or responsibility; it becomes control when the gift is used to claim ownership over decisions that are not theirs.",
  66: "Include the total purchase price, interest, insurance, maintenance, depreciation, risk, lost flexibility, and what the payment prevents you from saving or doing.",
  67: "Switch from protecting cash to attacking debt once the emergency buffer is adequate and the high-interest balance is no longer protecting you from a bigger risk.",
  68: "Status is a business tool when you can show it creates enough real revenue or trust to exceed its cost; otherwise it is expensive evidence for strangers.",
  69: "Let enough of the raise improve life to matter, but protect a meaningful share for savings before new spending becomes permanent.",
  70: "The ‘unexpected’ expense is usually a normal repair, medical cost, vehicle problem, home failure, or annual bill whose exact date was uncertain, not its existence.",
  71: "The limit is reached when the combined payments reduce your ability to handle essentials, save, absorb a setback, or freely say no to another obligation.",
  72: "Productive borrowing funds something expected to create durable income or capacity; consumption borrowing mainly moves today's spending into future paycheques.",
  73: "Avoid fixed expenses that would force you to stay in a job, relationship, or situation you already know you might need the freedom to leave.",
  74: "Labels like ethical, sustainable, healthy, natural, fair-trade, local, and cruelty-free can answer one issue without proving the whole person or business is good.",
  75: "A role difference is fair when it tracks relevant ability, responsibility, or function and remains open to real opportunity; it is unfair when the reason is only tradition or exclusion.",
  76: "Outsource choices that are low-stakes and do not shape your habits or values; keep deliberate control over choices that repeatedly shape character, attention, money, or relationships.",
  77: "Personalization serves freedom when it saves effort without narrowing your world; it becomes a trap when the system keeps you inside what already earns an easy click.",
  78: "Credit the person for the parts they actually create and perform, and credit the tool for the skill or polish it supplies.",
  79: "Maintain backups for failures that would cause serious harm, leave you helpless, or take too long to rebuild from scratch even if they are rarely needed.",
  80: "The questions worth answering are the ones about purpose, direction, responsibility, relationships, and what kind of life you are building, not merely how comfortable today feels.",
  81: "Function is strong evidence of purpose when the design repeatedly points to that end; it is weaker when the same function could be a side effect or secondary use.",
  82: "The more coordinated, specific, and functionally organized the outcome is, the more the explanation must account for how that organization was produced and preserved.",
  83: "Randomness creates possibilities; a preserving process keeps successful arrangements from being lost so useful structure can build over time.",
  84: "An explanation genuinely ends when it reaches something that does not depend on another instance of the same unresolved dependence.",
  85: "Voting is suitable for preferences and policy trade-offs; basic protections against unjust harm should not disappear merely because a majority dislikes the people protected.",
  86: "A strong moral feeling should trigger a closer look when it signals possible harm; afterward you still need reasons, facts, and a standard that works beyond the feeling itself.",
  87: "The facts that matter are necessity, evidence of harm, proportionality, duration, who is burdened, and whether the same rule respects protections that apply to everyone.",
  88: "Look for a concrete purpose, evidence of real burdens, proportionality, and consistent application; age and popularity alone do not turn a rule into a fair one.",
  89: "Exclusion needs a narrow, evidence-based threat to the conditions of open participation, not merely offensive views, criticism, or fear of losing an argument.",
  90: "Accountability changes behaviour between elections when decisions are transparent, conflicts are exposed, oversight has teeth, and incentives carry real consequences before the next vote.",
  91: "A strong team can supply specialist knowledge, but the leader still needs enough understanding to judge advice, ask good questions, and act when time is short.",
  92: "A temporary power needs a hard expiry, narrow scope, independent review, public reporting where possible, and a fresh burden of proof for any renewal.",
  93: "Try safe internal reporting, documentation, and responsible escalation first; go public when suppression, retaliation, or repeated failure shows those channels cannot correct serious wrongdoing.",
  94: "Use group data to place resources, then require person-specific reasons for stops, accusations, or penalties and keep measuring whether enforcement itself is distorting the data.",
  95: "Move from influence to coordination when there is evidence of shared planning or agreement, and to control only when one actor can direct another's decisions.",
  96: "Preserve both when possible: the information protects the content, while the original artifact can preserve unique evidence about origin, history, and authenticity.",
  97: "The claims must refer to the same subject, time, place, meaning, and relevant respect, and they must be impossible to both be true.",
  98: "Give enough context that a reasonable reader would not take away a materially different meaning from the source than the source actually expressed.",
  99: "Refuse to optimize any feature that predictably weakens a user's ability to stop, choose freely, or function well simply because that weakness improves the metric.",
  100: "A great result is too expensive when it requires sacrificing core character, serious duties, health, or relationships that the achievement cannot later replace.",
  101: "It becomes dishonest when you know the missing fact would materially change the other person's understanding or decision and you stay silent to preserve the mistaken impression.",
  102: "Show the date, ownership or context changes, what the old evidence proves, and what current evidence says so history is not presented as present fact.",
  103: "Be certain enough that a reasonable person can safely plan around your yes; if a real conflict is likely, give a tentative answer instead of a promise.",
  104: "A conflict of interest should raise the level of checking and make independent verification more important, but good evidence should still count once it survives that scrutiny.",
  105: "Help-seeking is limited to a real need, an appropriate person, and only the information needed to solve it; gossip spreads private facts for interest, bonding, or entertainment.",
  106: "Override confidentiality when there is a credible risk of serious harm that cannot reasonably be prevented while keeping the information private.",
  107: "Set a few clear no-go subjects, allow people to opt out without embarrassment, and treat discomfort as enough reason to stop without demanding a courtroom explanation.",
  108: "Poor delivery should lower confidence when it reveals carelessness, dishonesty, or unreliability about the claim; it should not outweigh stronger documents or direct evidence by itself.",
  109: "Repair your wording when a reasonable listener could honestly read it too broadly; blame the critic when they ignore a clear statement and attack a version you did not make.",
  110: "A deadline justifies choosing imperfect options when delay itself carries serious cost and the better alternative is not developed enough to be a real option.",
  111: "Reject the unsupported accusation clearly, then answer the legitimate concern on its own facts instead of using the bad premise as a reason to avoid the issue.",
  112: "A clearer definition has reasons that existed before the awkward example, fits the category's purpose, and works the same way on cases you like and dislike.",
  113: "Testimonials can justify a low-cost trial when failure is cheap; before a large commitment, you need the success rate and the outcomes of people who did not succeed.",
  114: "A cheap precaution can be reasonable when the possible harm is serious, the precaution is harmless, and you are not treating the weak claim as proven.",
  115: "Expert intuition should trigger investigation when it comes from relevant experience and identifies a plausible risk, but stronger tested evidence should still decide the claim.",
  116: "Prioritize one cause when evidence shows it contributes most and the intervention is tractable, while keeping other causes in view instead of calling the winner the only cause.",
  117: "Hold leaders accountable for the quality of the process: what evidence they had, which risks they accepted, and which warnings they reasonably should have addressed.",
  118: "Continue when the future benefit is still worth the future cost; stop when the main reason is simply that you have already spent too much to quit.",
  119: "Implement the imperfect system when the expected improvement is meaningful, the new harms are manageable, and waiting has a larger real cost than acting.",
  120: "A compromise is independently good when it has its own reasons, solves the real problem, and would still make sense even if it were not halfway between two positions.",
  121: "An exception is principled when it follows a relevant difference tied to the rule's purpose and you would grant it equally to someone you dislike.",
  122: "Finding nothing matters when the search had a good chance of finding the thing if it were there; weak coverage supports only a weak conclusion.",
  123: "Compare choices with and without the system's intervention while holding prediction constant; a difference shows influence rather than knowledge alone.",
  124: "Fix the subject, time, place, meaning, and scope first; only then can opposite statements be called genuine contradictions.",
  125: "Clues add real weight when they come from sufficiently independent sources or mechanisms rather than repeating the same underlying information.",
  126: "Communication can manage preferences, habits, and negotiable expectations; differences that determine children, family duties, core values, or life direction eventually choose the household's path.",
  127: "Give their interests enough weight to address the real cost fairly, but keep final authority with the people who actually own the decision and its main consequences.",
  128: "Real tie-break authority needs defined scope, prior consultation, a duty to serve the household, responsibility for consequences, and no power over ordinary preferences.",
  129: "Yes. Leadership can be distributed when each person carries real responsibility in different areas and both respect the other's competence instead of competing for rank.",
  130: "Outside help is needed when harm repeats, fear grows, repair attempts fail, safety worsens, or the couple is normalizing behaviour they can no longer judge clearly.",
  131: "Intentions, exclusivity, major values, deal-breakers, boundaries, and the general direction of the relationship should become clearer as attachment grows, even if the final decision still needs time.",
  132: "A question is decision-changing when a different answer could reasonably reverse or seriously alter the choice; the rest are uncertainties you can keep learning after acting.",
  133: "An unreliable source should increase verification, not trigger automatic rejection; test what can be checked and avoid trusting unverified details simply because one part was right.",
  134: "Context clarifies when it explains scope, purpose, exceptions, or how rules fit together; it becomes an escape when it is invented only to avoid an inconvenient clear requirement.",
  135: "Clarify when the wording may be sloppy but the underlying goal could be coherent; dismiss only after confirming the contradiction is really the intended requirement.",
  136: "Stress reveals stable character when the pressure resembles real life and the same behaviour repeats across situations; one artificial trigger may reveal only that trigger.",
  137: "Use more structure when the child lacks the capacity to understand or self-manage, then add explanation and choice as soon as they can meaningfully carry them.",
  138: "Reduce control in steps as the child repeatedly shows honesty, self-restraint, good judgement, and willingness to seek help; restore limits when risk exceeds demonstrated maturity.",
  139: "Assertive escalation stays focused on the problem, the remedy, and clear boundaries; anger takes control when humiliation, revenge, or emotional release becomes the goal.",
  140: "Context should change a consequence when it changes intent, risk, repetition, or responsibility; the parent's tiredness, embarrassment, or bad mood should not.",
  141: "Useful consequences are safe, proportionate, and within the child's developmental ability to learn from; serious health, safety, or adult-management failures remain the adult's responsibility.",
  142: "Choose timing by the seriousness and urgency of the falsehood, the likely harm of waiting, the need for public correction, and the person's dignity.",
  143: "Encouragement is honest when it names real strengths or progress, admits the real problem, and gives hope tied to something the person can actually do.",
  144: "Tell the smallest number of trustworthy, mature people who can help you think or stay safe, not the largest audience willing to take your side.",
  145: "Their agreement becomes stronger when they have enough facts, hear more than one perspective, and reach the same conclusion without merely repeating the same account.",
  146: "Ready enough means the core values, character, compatibility, responsibilities, and major future questions are sufficiently clear, while accepting that no lifelong decision comes with total certainty.",
  147: "Listen seriously, investigate valid concerns, and adjust when the advice is right, but keep respectful disagreement possible because adult responsibility cannot be outsourced.",
  148: "Move to closer monitoring when there are specific, credible signs of safety risk, serious harm, or dangerous behaviour, not merely discomfort with growing privacy.",
  149: "Prevent the immediate disaster if it is disproportionate, but attach clear conditions that make the person carry repayment, planning, or changed behaviour rather than expecting another rescue.",
  150: "Make recurring responsibilities, ownership, and invisible planning clear enough that nobody can hide behind vagueness, while allowing temporary imbalance when real circumstances change.",
  151: "Pay more for flexibility when there is a meaningful chance your needs will change and the exit option is worth the premium; otherwise decide and take the discount.",
  152: "No single company belief should control enough of your future that one bad outcome can derail an essential life goal.",
  153: "If the date could be near enough that a market loss would block the goal, keep that portion safe and invest only money that can tolerate waiting.",
  154: "Rewards are saving money only when the purchase was already planned and would happen without the points; if the reward changes the purchase, it is driving spending.",
  155: "Future value is durable enough when the education, asset, or capacity has strong evidence of lasting benefit and the repayment still leaves reasonable flexibility if things go badly.",
  156: "Exceptional success should outweigh broader evidence only when you can show the method, not just luck or survivorship, reliably explains why that person won.",
  157: "Labels like retirement account, tax-free account, savings account, brokerage account, and education account describe containers; they do not tell you what the money inside actually owns.",
  158: "Automate a percentage toward emergency savings, debt, or long-term goals while keeping a minimum cash buffer so the rule bends with variable income.",
  159: "A lifestyle cost may be justified when the role builds durable skills, credentials, network, or future options that materially improve life after the sacrifice ends.",
  160: "Decide in advance what the extra capacity is for, cap how much work or distraction can claim, and protect the rest before expectations expand.",
  161: "It is temporary when it has a clear end date or trigger, a defined reason, and a deliberate return to normal boundaries once the emergency ends.",
  162: "Only genuine emergencies, essential family needs, time-sensitive work you truly own, and critical logistics deserve first access; feeds and ordinary messages can wait.",
  163: "Explore when you are still learning what deserves your attention; go deep when something matters enough that understanding or enjoyment requires staying past the first urge to switch.",
  164: "Pay when the service is valuable enough that you would rather exchange a known amount of money than give away persistent data, behavioural profiling, or attention.",
  165: "Reaction is useful when it signals urgency, public concern, or something needing investigation; it is weak evidence of how common, representative, or true the event is.",
  166: "Keep researching only if a specific unanswered question could materially change the decision, the safety of starting, or the first step you should take.",
  167: "Check the claims that drive the decision, verify important numbers and sources, understand the main reasoning, and know enough to answer basic challenges before attaching your name.",
  168: "Directly check sources supporting the central numbers, unusual claims, and anything that would change the decision if wrong; sample lower-stakes background claims.",
  169: "Enough to expose yourself regularly to serious opposing evidence and unfamiliar perspectives, but not so much random material that relevance and attention disappear.",
  170: "Sacrifice enough reach to avoid distortion and humiliation; a correction that travels farther by becoming unfair can damage the truth it is supposed to defend.",
  171: "Enough silence for your mind to move past restlessness and begin producing its own thoughts; that may be ten minutes for one person and much longer for another.",
  172: "It is restorative when it leaves you genuinely recovered and still able to pursue what matters; it is replacing life when it repeatedly crowds those things out.",
  173: "Only signals tied to a real emergency or genuinely time-sensitive duty should interrupt protected time; everything else can use a normal channel and wait.",
  174: "Only a substantial security gain against a realistic threat justifies storing hard-to-replace behavioural or biometric data, and the collection should stay minimal.",
  175: "Enough money should let you buy back time for relationships, health, service, rest, and meaningful work now, not merely keep moving the safety target farther away.",
  176: "Choose the rule you would accept before knowing which side benefits, and change it only for a relevant difference you would recognize against your own team too.",
  177: "Collect the facts that actually affect need, urgency, and harm for everyone, then prioritize those facts rather than rewarding whoever has the most vivid story.",
  178: "You still hold the person responsible for chosen wrongdoing, but you judge force, punishment, and unnecessary harm more carefully because the target remains a full human being.",
  179: "State the failure accurately, show its scale and evidence, separate the problem from contempt for the whole group, and keep the goal focused on repair.",
  180: "Test interventions and compare outcomes: if changing the environment moves the result, structure matters; if differences remain after that, norms or behaviour may explain the rest.",
  181: "An obstacle changes affordability when people still want the same thing but cannot carry the cost; it changes preference when the condition changes whether they want it at all.",
  182: "Both matter, but rewards usually reveal the stronger reality: what people are punished or promoted for will often overpower what the policy says they may do.",
  183: "Use a group statistic as a cautious starting probability when individual information is missing; drop it quickly when person-specific evidence arrives.",
  184: "Look for predictions that differ: if heat drives both, changes should follow temperature broadly; if ice-cream crowds matter, theft should rise especially around those locations.",
  185: "Hypocrisy should lower trust when it shows the person's judgement or honesty is unreliable in the relevant area, but the evidence still needs its own evaluation.",
  186: "Warn only about the specific risk supported by current evidence, label what remains unverified, and avoid repeating broader accusations until they are confirmed.",
  187: "The different judgement needs a relevant difference in harm, history, power, duty, or circumstance that would still matter if your preferred group were not involved.",
  188: "State only what the verified material shows, identify what is still unknown, avoid assigning blame beyond the evidence, and update the account as verification improves.",
  189: "Meaningful contribution has a realistic target, fits your capacity and duties, and produces some plausible benefit; performance mainly signals that you care while neglecting more effective responsibilities.",
  190: "It becomes surrender when you stay mainly because of pressure, fear of looking boring, or difficulty saying no after you already know the better choice for yourself.",
  191: "Define the purpose of the rule, name the differences that genuinely matter, require reasons for every exception, and apply those reasons consistently regardless of status.",
  192: "Evidence of effectiveness, correct dose, side effects, interactions, quality control, manufacturing consistency, and whether the treatment fits the actual problem matter more than origin.",
  193: "One bad argument should remove that argument and raise scrutiny of the advocate, but it should damage the rest only if it reveals broader unreliability in the evidence.",
  194: "Context can explain what someone knew, could realistically do, and how blame should be measured; it cannot make clear cruelty or injustice become good simply because it was common.",
  195: "Relieve states that are overwhelming, disabling, or no longer serving a useful protective role; listen first when pain may be warning about harm, guilt, boundaries, or needed change.",
  196: "Compare words with costly behaviour: a belief is more likely a real motive when people sacrifice for it, and more likely a justification when it changes with their material interests.",
  197: "An expert should be able to state the relevant principle, show why it applies, identify the key evidence, and explain what would change the conclusion.",
  198: "Whichever one is weaker needs attention, but good speech requires both: tell the truth and ask whether saying it now, this way, serves a legitimate good.",
  199: "Praise the good act specifically and sincerely, then judge unrelated wrongdoing separately instead of letting one virtue purchase immunity from correction.",
  200: "A priority has enough action when it appears regularly in your calendar and behaviour; it is living on speeches when time repeatedly goes elsewhere despite your stated importance."
});
